name: Test FrodoPIR Scheme

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
        build_type: [debug, release]
        test_type: [standard, asan, ubsan]
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4

    - name: Setup Google Test
      uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.15.2

    - name: Build and Test (${{matrix.os}}, ${{ matrix.compiler }}, ${{ matrix.build_type }}, ${{ matrix.test_type }})
      run: |
        CXX=${{ matrix.compiler }}
        if [[ ${{ matrix.test_type }} == "standard" ]]; then
          make test -j
        else
          make ${{ matrix.build_type }}_${{ matrix.test_type }}_test -j
        fi

    - name: Run Examples
      if: ${{ matrix.test_type == 'standard' && matrix.build_type == 'release' }}
      run: |
        CXX=${{ matrix.compiler }} make example -j
